package Model;
// Generated Sep 30, 2014 12:09:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Kwek generated by hbm2java
 */
public class Kwek  implements java.io.Serializable {


     private int kwekid;
     private Account account;
     private String message;
     private Set accounts = new HashSet(0);

    public Kwek() {
    }

	
    public Kwek(Account account) {
        this.account = account;
    }
    public Kwek(Account account, String message, Set accounts) {
       this.account = account;
       this.message = message;
       this.accounts = accounts;
    }
   
    public Integer getKwekid() {
        return this.kwekid;
    }
    
    public void setKwekid(Integer kwekid) {
        this.kwekid = kwekid;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }

    @Override
    public String toString() {
        return account + ": " + message;
    }
    
    


}


